version: '2.3'
services: 
  gpt-gpu:
    build: 
      context: .
      dockerfile: containers/gpt-2/Dockerfile.gpu
    runtime: nvidia
    tty: true
    stdin_open: true
    volumes: 
      - "./:/handey"
    ports:
      - "127.0.0.2:8888:8888"
      - "127.0.0.2:8000:8000"
#    command: ["./src/rest.py"]
#  gpt-cpu:
#    build: 
#      context: .
#      dockerfile: containers/gpt-2/Dockerfile.cpu
#    tty: true
#    stdin_open: true
#    volumes: 
#      - "./:/handey"
#    ports:
#      - "127.0.0.3:8888:8888"
#      - "127.0.0.3:8000:8000"
#  gpt-tpu:
#    build: 
#      context: .
#      dockerfile: containers/gpt-2/Dockerfile.cpu
#    tty: true
#    stdin_open: true
#    volumes: 
#      - "./:/handey"
#    ports:
#      - "127.0.0.4:8888:8888"
#      - "127.0.0.4:8000:8000"
#  neo4j:
#    build: 
#      context: .
#      dockerfile: containers/neo4j/Dockerfile
#    tty: true
#    stdin_open: true
#    volumes: 
#      - "./:/handey"
#    ports:
#      - "127.0.0.5:7474:7474"
#      - "127.0.0.5:7473:7473"
#      - "127.0.0.5:7687:7687"
#    environment:
#        - EXTENSION_SCRIPT=/tmp/neo4j-init.sh 
